# -*- coding: utf-8 -*-
"""BERT_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaT0-a9NimBHF2cNZdPd31AmUxxBk3Ia
"""

# Project Dependency

!pip install -q bert-extractive-summarizer

!pip install -q spacy

!pip install transformers==3.3.0

!pip install folium==0.2.1

!pip install -q neuralcoref

!pip install sentencepiece

# Main Code

from summarizer import Summarizer
from pprint import pprint

# Mounting  Google Drive with Colab
from google.colab import drive 
drive.mount('/content/drive')

import os
os.listdir()
# cd drive
# os.listdir()
# cd MyDrive
# cd Colab Notebooks/







# os.listdir()

# Open File in same Destination Folder
with open("samplefile.txt", 'r') as file:
    data = file.read().replace('\n', '')

data = data.replace("\ufeff", "")

# Data upload in model for processing
model = Summarizer()
result = model(data, num_sentences=5, min_length=60)
full = ''.join(result)

# Final Result
pprint(full)





